In [74]:
%lsmagic

Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %code_wrap  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%code_wrap  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python  %%python2  %%python3  %%ruby  %%script  %%sh  %%svg  %%sx  %%system  %%time  %%timeit  %%writefile

Automagic is ON, % prefix IS NOT needed for line magics.

In [75]:
%%HTML

<html>

<body>

<h1>Hello World</h3>

<p>Welcome to my website</p>

</body>

</html>

$\int \frac{1}{x} dx = \ln \left| x \right| + C$

# Oben ein paar übungen, was man Spezielles machen kann.

In [76]:
import plotly.graph_objs as go
import plotly.express as px
import pandas as pd
import plotly.io as pix

# Set the renderer to 'notebook'
# pio.renderers.default = 'iframe'

In [77]:
df = pd.read_csv("../assets/strassenverkehrsunfallorte_sg.csv", sep=";")
df.head()

,﻿AccidentUID,AccidentType,AccidentType_de,AccidentType_fr,AccidentType_it,AccidentType_en,AccidentSeverityCategory,AccidentSeverityCategory_de,AccidentSeverityCategory_fr,AccidentSeverityCategory_it,...,AccidentMonth_fr,AccidentMonth_it,AccidentMonth_en,AccidentWeekDay,AccidentWeekDay_de,AccidentWeekDay_fr,AccidentWeekDay_it,AccidentWeekDay_en,AccidentHour,AccidentHour_text
0,EF4A4035085402D2E0430A839427E2AD,at8,Fussgängerunfall,accident impliquant des piétons,Incidente con pedoni,Accident involving pedestrian(s),as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,novembre,Novembre,01-11-01,aw404,Donnerstag,jeudi,Giovedì,01-01-04,11,11h-12h
1,ED3EEAA66FDF014AE0430A839427F196,at3,Abbiegeunfall,accident en quittant une route,Incidente nello svoltare,Accident when turning left or right,as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,novembre,Novembre,01-11-01,aw405,Freitag,vendredi,Venerdì,01-01-05,14,14h-15h
2,ED5433FDDA990170E0430A8394279BE0,at8,Fussgängerunfall,accident impliquant des piétons,Incidente con pedoni,Accident involving pedestrian(s),as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,novembre,Novembre,01-11-01,aw405,Freitag,vendredi,Venerdì,01-01-05,16,16h-17h
3,ED441C9CF7B501FCE0430A8394279F8A,at3,Abbiegeunfall,accident en quittant une route,Incidente nello svoltare,Accident when turning left or right,as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,novembre,Novembre,01-11-01,aw401,Montag,lundi,Lunedí,NaN,18,18h-19h
4,EF988DF2357600CAE0430A839427BF7F,at8,Fussgängerunfall,accident impliquant des piétons,Incidente con pedoni,Accident involving pedestrian(s),as3,Unfall mit Leichtverletzten,accident avec blessés légers,Incidente con feriti leggeri,...,décembre,Dicembre,01-12-01,aw404,Donnerstag,jeudi,Giovedì,01-01-04,17,17h-18h

In [78]:
df.shape

(2055, 39)

In [79]:
df.columns

Index(['﻿AccidentUID', 'AccidentType', 'AccidentType_de', 'AccidentType_fr',
       'AccidentType_it', 'AccidentType_en', 'AccidentSeverityCategory',
       'AccidentSeverityCategory_de', 'AccidentSeverityCategory_fr',
       'AccidentSeverityCategory_it', 'AccidentSeverityCategory_en',
       'AccidentInvolvingPedestrian', 'AccidentInvolvingBicycle',
       'AccidentInvolvingMotorcycle', 'RoadType', 'RoadType_de', 'RoadType_fr',
       'RoadType_it', 'RoadType_en', 'AccidentLocation_CHLV95_E',
       'AccidentLocation_CHLV95_N', 'Location', 'CantonCode',
       'MunicipalityCode', 'MunicipalityName', 'AccidentYear', 'AccidentMonth',
       'Month_Year', 'AccidentMonth_de', 'AccidentMonth_fr',
       'AccidentMonth_it', 'AccidentMonth_en', 'AccidentWeekDay',
       'AccidentWeekDay_de', 'AccidentWeekDay_fr', 'AccidentWeekDay_it',
       'AccidentWeekDay_en', 'AccidentHour', 'AccidentHour_text'],
      dtype='object')

In [80]:
df = df.iloc[:, [0, 2, 7, 11, 12, 13, 15, 21, 25, 26, 33, 37]]
df.head()

,﻿AccidentUID,AccidentType_de,AccidentSeverityCategory_de,AccidentInvolvingPedestrian,AccidentInvolvingBicycle,AccidentInvolvingMotorcycle,RoadType_de,Location,AccidentYear,AccidentMonth,AccidentWeekDay_de,AccidentHour
0,EF4A4035085402D2E0430A839427E2AD,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Hauptstrasse,"47.41145015680007, 9.366495541935732",2013,11,Donnerstag,11
1,ED3EEAA66FDF014AE0430A839427F196,Abbiegeunfall,Unfall mit Leichtverletzten,False,False,False,Hauptstrasse,"47.42742094080175, 9.374485095757596",2013,11,Freitag,14
2,ED5433FDDA990170E0430A8394279BE0,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Nebenstrasse,"47.426503043920654, 9.37610889837079",2013,11,Freitag,16
3,ED441C9CF7B501FCE0430A8394279F8A,Abbiegeunfall,Unfall mit Leichtverletzten,False,False,False,Hauptstrasse,"47.39805416953188, 9.296751574428464",2013,11,Montag,18
4,EF988DF2357600CAE0430A839427BF7F,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Hauptstrasse,"47.43694750539271, 9.38793267101484",2013,12,Donnerstag,17

In [81]:
df.dtypes

AccidentUID                   object
AccidentType_de                object
AccidentSeverityCategory_de    object
AccidentInvolvingPedestrian      bool
AccidentInvolvingBicycle         bool
AccidentInvolvingMotorcycle      bool
RoadType_de                    object
Location                       object
AccidentYear                    int64
AccidentMonth                   int64
AccidentWeekDay_de             object
AccidentHour                    int64
dtype: object

In [82]:
column_name_mapping = {
    'AccidentUID': 'ID',
    'AccidentType_de': 'Unfalltyp',
    'AccidentSeverityCategory_de': 'Unfallschwere',
    'AccidentInvolvingPedestrian': 'Fussgänger',
    'AccidentInvolvingBicycle': 'Fahrrad',
    'AccidentInvolvingMotorcycle': 'Motorrad',
    'RoadType_de': 'Strassentyp',
    'Location': 'Location',
    'AccidentYear': 'Jahr',
    'AccidentMonth': 'Monat',
    'AccidentWeekDay_de': 'Wochentag',
    'AccidentHour': 'Stunde'
}

In [83]:
df.rename(columns=column_name_mapping, inplace=True)

In [84]:
df[['Breitengrad', 'Längengrad']] = df['Location'].str.split(',', expand=True).astype(float)

In [85]:
df.drop(columns=['Location'], inplace=True)

In [86]:
df['Datum'] = pd.to_datetime(df['Jahr'].astype(str) + '-' + df['Monat'].astype(str) + '-01')

In [87]:
df.head()

,﻿AccidentUID,Unfalltyp,Unfallschwere,Fussgänger,Fahrrad,Motorrad,Strassentyp,Jahr,Monat,Wochentag,Stunde,Breitengrad,Längengrad,Datum
0,EF4A4035085402D2E0430A839427E2AD,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Hauptstrasse,2013,11,Donnerstag,11,47.411450,9.366496,2013-11-01
1,ED3EEAA66FDF014AE0430A839427F196,Abbiegeunfall,Unfall mit Leichtverletzten,False,False,False,Hauptstrasse,2013,11,Freitag,14,47.427421,9.374485,2013-11-01
2,ED5433FDDA990170E0430A8394279BE0,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Nebenstrasse,2013,11,Freitag,16,47.426503,9.376109,2013-11-01
3,ED441C9CF7B501FCE0430A8394279F8A,Abbiegeunfall,Unfall mit Leichtverletzten,False,False,False,Hauptstrasse,2013,11,Montag,18,47.398054,9.296752,2013-11-01
4,EF988DF2357600CAE0430A839427BF7F,Fussgängerunfall,Unfall mit Leichtverletzten,True,False,False,Hauptstrasse,2013,12,Donnerstag,17,47.436948,9.387933,2013-12-01

In [88]:
df.dtypes

AccidentUID             object
Unfalltyp                object
Unfallschwere            object
Fussgänger                 bool
Fahrrad                    bool
Motorrad                   bool
Strassentyp              object
Jahr                      int64
Monat                     int64
Wochentag                object
Stunde                    int64
Breitengrad             float64
Längengrad              float64
Datum            datetime64[ns]
dtype: object

In [89]:
df.to_csv('unfallorte.csv', index=False)

#### Jetzt möchte ich mit Hilfe einer Pivot-Table feststellen, wie sich die Vorfälle auf Wochentag und Stunde verteilen

>>> df = pd.DataFrame({"A": ["foo", "foo", "foo", "foo", "foo",
...                          "bar", "bar", "bar", "bar"],
...                    "B": ["one", "one", "one", "two", "two",
...                          "one", "one", "two", "two"],
...                    "C": ["small", "large", "large", "small",
...                          "small", "large", "small", "small",
...                          "large"],
...                    "D": [1, 2, 2, 3, 3, 4, 5, 6, 7],
...                    "E": [2, 4, 5, 5, 6, 6, 8, 9, 9]})

df

dfp = pd.pivot_table(df, values=df, index="A", columns="C")
dfp

In [90]:
df['Wochentag'] = pd.Categorical(df['Wochentag'])

In [91]:
df_weekday_hour = pd.pivot_table(df, values="Unfalltyp", index='Wochentag', columns='Stunde', aggfunc='size', fill_value=0)
df_weekday_hour

Stunde,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
Wochentag,,,,,,,,,,,,,,,,,,,,,
Dienstag,1,0,1,1,1,3,15,34,15,14,...,23,18,25,51,31,12,9,9,5,2
Donnerstag,2,3,3,2,1,5,14,39,19,13,...,16,21,38,49,17,19,11,12,10,9
Freitag,5,2,3,1,2,1,11,16,14,12,...,21,25,38,50,26,21,6,9,10,5
Mittwoch,3,3,1,3,3,4,9,19,13,8,...,17,28,20,47,22,17,7,7,13,3
Montag,0,0,0,1,1,4,15,32,14,14,...,13,18,25,52,18,16,9,7,4,4
Samstag,4,2,3,4,3,3,1,4,8,3,...,18,17,17,21,14,6,7,5,7,7
Sonntag,6,8,5,5,4,4,1,3,5,4,...,6,11,17,13,9,7,5,3,1,2

In [92]:
df_weekday_hour = df_weekday_hour.reset_index()
df_weekday_hour

Stunde,Wochentag,0,1,2,3,4,5,6,7,8,...,14,15,16,17,18,19,20,21,22,23
0,Dienstag,1,0,1,1,1,3,15,34,15,...,23,18,25,51,31,12,9,9,5,2
1,Donnerstag,2,3,3,2,1,5,14,39,19,...,16,21,38,49,17,19,11,12,10,9
2,Freitag,5,2,3,1,2,1,11,16,14,...,21,25,38,50,26,21,6,9,10,5
3,Mittwoch,3,3,1,3,3,4,9,19,13,...,17,28,20,47,22,17,7,7,13,3
4,Montag,0,0,0,1,1,4,15,32,14,...,13,18,25,52,18,16,9,7,4,4
5,Samstag,4,2,3,4,3,3,1,4,8,...,18,17,17,21,14,6,7,5,7,7
6,Sonntag,6,8,5,5,4,4,1,3,5,...,6,11,17,13,9,7,5,3,1,2

In [98]:
df_weekday_hour.shape

(7, 24)

In [99]:
df_weekday_hour.dtypes

Stunde
0     int64
1     int64
2     int64
3     int64
4     int64
5     int64
6     int64
7     int64
8     int64
9     int64
10    int64
11    int64
12    int64
13    int64
14    int64
15    int64
16    int64
17    int64
18    int64
19    int64
20    int64
21    int64
22    int64
23    int64
dtype: object

In [107]:
column_types = df_weekday_hour.columns.to_series().dtypes

print(column_types)

int64

df_weekday_hour.drop("index", axis=1, inplace=True)
df_weekday_hour.shape

In [93]:
df_help = df[["Unfalltyp", "Wochentag", "Stunde"]]
df['Wochentag'] = pd.Categorical(df['Wochentag'])
print(df_help.head())

          Unfalltyp   Wochentag  Stunde
0  Fussgängerunfall  Donnerstag      11
1     Abbiegeunfall     Freitag      14
2  Fussgängerunfall     Freitag      16
3     Abbiegeunfall      Montag      18
4  Fussgängerunfall  Donnerstag      17

In [94]:
df_help.dtypes

Unfalltyp      object
Wochentag    category
Stunde          int64
dtype: object

In [95]:
df_weekday_hour = pd.pivot_table(df_help, values="Stunde", index='Wochentag', columns='Stunde', aggfunc='size', fill_value=0)

# If needed, reset the index to make 'Wochentag' a column again
# df_weekday_hour = df_weekday_hour.reset_index()

print(df_weekday_hour)

Stunde      0   1   2   3   4   5   6   7   8   9   ...  14  15  16  17  18  \
Wochentag                                           ...
Dienstag     1   0   1   1   1   3  15  34  15  14  ...  23  18  25  51  31
Donnerstag   2   3   3   2   1   5  14  39  19  13  ...  16  21  38  49  17
Freitag      5   2   3   1   2   1  11  16  14  12  ...  21  25  38  50  26
Mittwoch     3   3   1   3   3   4   9  19  13   8  ...  17  28  20  47  22
Montag       0   0   0   1   1   4  15  32  14  14  ...  13  18  25  52  18
Samstag      4   2   3   4   3   3   1   4   8   3  ...  18  17  17  21  14
Sonntag      6   8   5   5   4   4   1   3   5   4  ...   6  11  17  13   9

Stunde      19  20  21  22  23
Wochentag
Dienstag    12   9   9   5   2
Donnerstag  19  11  12  10   9
Freitag     21   6   9  10   5
Mittwoch    17   7   7  13   3
Montag      16   9   7   4   4
Samstag      6   7   5   7   7
Sonntag      7   5   3   1   2

[7 rows x 24 columns]

In [96]:
df = pd.read_csv('https://raw.githubusercontent.com/plotly/datasets/master/solar.csv')
print(df.head())

        State  Number of Solar Plants  Installed Capacity (MW)  \
0  California                     289                     4395
1     Arizona                      48                     1078
2      Nevada                      11                      238
3  New Mexico                      33                      261
4    Colorado                      20                      118

   Average MW Per Plant  Generation (GWh)
0                  15.3             10826
1                  22.5              2550
2                  21.6               557
3                   7.9               590
4                   5.9               235

In [97]:
# Define the custom sorting order in German
day_order = ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag']

# Convert the 'Wochentag' column to categorical data with the  day order
result_df['Wochentag'] = pd.Categorical(result_df['Wochentag'], categories=day_order, ordered=True)

# Sort the DataFrame by 'Wochentag' in the specified order
result_df = result_df.sort_values(by='Wochentag')
print(result_df)

# Optionally, remove the categorical data type if no longer needed
result_df['Wochentag'] = result_df['Wochentag'].astype(str)

NameError: name 'result_df' is not defined

##### Im Prinzip habe ich jetzt meine Datei. Ich wende aber im Folgenden Pandas AI an, um den Datensatz noch etwas besser kennen zu lernen

In [ ]:
from pandasai import PandasAI
from pandasai.llm.openai import OpenAI
import os

In [ ]:
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
model = "gpt-3.5-turbo"
llm = OpenAI(api_token=OPENAI_API_KEY, model = model)

In [ ]:
pandas_ai = PandasAI(llm, conversational= False)

In [ ]:
pandas_ai.run(df, prompt="wie viele Zeilen und Spalten hat der Dataframe")

In [ ]:
pandas_ai.run(df, prompt="Wie teilen sich die Zeilen in Abhängigkeit der Spalten auf?")